apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: redis-operator
  namespace: infraforge-argocd
spec:
  destination:
    namespace: infraforge-operators
    server: https://kubernetes.default.svc
  project: infraforge-dev
  source:
    chart: redis-operator
    repoURL: https://spotahome.github.io/redis-operator
    targetRevision: 3.2.9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
