apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-business-appset
  namespace: infraforge-argocd
spec:
  generators:
    - git:
        directories:
          - path: manifests/platform-cluster/apps/dev/business-apps/*
        repoURL: https://github.com/NimbusProTch/PaaS-Platform.git
        revision: main
  template:
    metadata:
      name: dev-business-{{.path.basenameNormalized}}
      namespace: infraforge-argocd
    spec:
      destination:
        namespace: demo-dev
        server: https://kubernetes.default.svc
      project: infraforge-dev
      source:
        path: '{{.path.path}}'
        repoURL: https://github.com/NimbusProTch/PaaS-Platform.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
