apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-platform-appset
  namespace: infraforge-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gaskin1/PaaS-Platform.git
        revision: feature/clean-platform
        files:
          - path: "manifests/apps/dev/platform-apps/*/Chart.yaml"
  template:
    metadata:
      name: 'dev-platform-{{path[2]}}'
      namespace: infraforge-argocd
    spec:
      project: infraforge-dev
      source:
        repoURL: https://github.com/gaskin1/PaaS-Platform.git
        targetRevision: feature/clean-platform
        path: '{{path.path | dir}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}-dev'  # e.g., vault-dev, istio-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true