apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-platform-appset
  namespace: infraforge-argocd
spec:
  generators:
    - git:
        directories:
          - path: manifests/platform-cluster/apps/prod/platform-apps/*
        repoURL: https://github.com/NimbusProTch/PaaS-Platform.git
        revision: main
  goTemplate: true
  template:
    metadata:
      name: prod-platform-{{.path.basename}}
      namespace: infraforge-argocd
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: https://kubernetes.default.svc
      project: infraforge-prod
      source:
        path: '{{.path.path}}'
        repoURL: https://github.com/NimbusProTch/PaaS-Platform.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
