
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backoffice
  namespace: finance-dev
  labels:
    app: backoffice
    tenant: finance
    environment: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: backoffice-finance-dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backoffice
            port:
              number: 80