apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-nginx-config
  namespace: finance-dev
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /api/health {
            return 200 '{"status":"healthy","app":"backoffice","tenant":"finance","environment":"dev"}';
            add_header Content-Type application/json;
        }
        
        location /api/info {
            return 200 '{"name":"InfraForge Backoffice","version":"1.0.0","profile":"dev"}';
            add_header Content-Type application/json;
        }
    }