apiVersion: v1
kind: Service
metadata:
  name: backoffice
  namespace: finance-dev
  labels:
    app: backoffice
    tenant: finance
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: backoffice