apiVersion: v2
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.25.0
description: HashiCorp Vault for finance-dev
name: vault
type: application
version: 0.1.0
