files:
- .kratix/finance-dev-nonprod.yaml
- apps/dev/business-apps/backoffice/configmap.yaml
- apps/dev/business-apps/backoffice/deployment.yaml
- apps/dev/business-apps/backoffice/helm-values.yaml
- apps/dev/business-apps/backoffice/ingress.yaml
- apps/dev/business-apps/backoffice/kustomization.yaml
- apps/dev/business-apps/backoffice/nginx-config.yaml
- apps/dev/business-apps/backoffice/service.yaml
- apps/dev/business-apps/nginx/helm-values.yaml
- apps/dev/business-apps/nginx/kustomization.yaml
- apps/dev/platform-apps/vault/Chart.yaml
- apps/dev/platform-apps/vault/values.yaml
- appsets/dev/business-appset.yaml
- appsets/dev/operator-appset.yaml
- appsets/dev/platform-appset.yaml
- argocd/dev/project.yaml
- metadata.yaml
- operators/dev/postgresql/cloudnative-pg-operator.yaml
- operators/dev/redis/redis-operator.yaml
