apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-operator-system
resources:
- deployment.yaml
images:
- name: platform-operator
  newName: ghcr.io/nimbusprotch/platform-operator
  newTag: latest
