apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-superuser
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres-dev-{{ .Values.tenant }}-{{ randAlphaNum 12 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-app-user
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.bootstrap.initdb.owner }}
  password: app-dev-{{ .Values.tenant }}-{{ randAlphaNum 12 }}