apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: cloudnative-pg
  namespace: infraforge-argocd
spec:
  destination:
    namespace: infraforge-operators
    server: https://kubernetes.default.svc
  project: infraforge-dev
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.20.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
