apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: platform-cluster
  namespace: kratix-platform-system
spec:
  path: .
  stateStoreRef:
    name: platform-bucket
    kind: BucketStateStore