apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  username: Z2Fza2luMQ==  # base64 encoded: gaskin1
  password: Z2hwXzM2eG1DSW4wbW1SM0hjY1FvMmJoa0FLeEoxWWxXVzI2NnQ4dg==  # base64 encoded token