apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  id_rsa: |
$(cat /tmp/kratix-deploy-key | base64)
  known_hosts: |
$(ssh-keyscan github.com 2>/dev/null | base64)