apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-env-configuration
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="minio-dev-{{ .Values.tenant }}-{{ randAlphaNum 12 }}"