apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infraforge-prod
  namespace: infraforge-argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: InfraForge Prod Environment
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      policies:
        - p, proj:infraforge-prod:admin, applications, *, infraforge-prod/*, allow
    - name: developer
      policies:
        - p, proj:infraforge-prod:developer, applications, get, infraforge-prod/*, allow
        - p, proj:infraforge-prod:developer, applications, sync, infraforge-prod/*, allow, * * 6-14 * 1-5
  sourceRepos:
    - '*'
