apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: minio
    tenant: {{ .Values.tenant }}
    environment: {{ .Values.environment }}
    profile: prod
    managed-by: infraforge
spec:
  configuration:
    name: {{ .Values.clusterName }}-env-configuration
  pools:
    - servers: {{ .Values.replicas }}
      name: pool-0
      volumesPerServer: {{ .Values.volumesPerServer }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.storage.storageClass }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.storage.size }}
      resources: {{- toYaml .Values.resources | nindent 8 }}
  requestAutoCert: false
