apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/platform.infraforge.io_applicationclaims.yaml
- bases/platform.infraforge.io_bootstrapclaims.yaml
- bases/platform.infraforge.io_platformclaims.yaml
