apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applicationset.yaml

# Environment specific patches
patches:
  - target:
      kind: ApplicationSet
      name: nonprod-apps
    patch: |-
      - op: add
        path: /spec/syncPolicy
        value:
          preserveResourcesOnDeletion: false