environment: dev
fullnameOverride: nginx
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: 1.25-alpine
ingress:
  className: nginx
  enabled: true
  host: nginx.demo.local
  tls: false
nameOverride: nginx
namespace: demo-dev
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  port: 80
  type: ClusterIP
tenant: demo
